# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: Hello World
description: Greet someone and record the time
inputs:
  greeting:
    description: the greeting to use
    required: false
    default: Hello
  who-to-greet:
    description: Who to greet
    required: true
    default: World
outputs:
  time:
    description: The time we greeted you
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.greeting }}
    - ${{ inputs.who-to-greet }}
