# https://docs.github.com/en/actions/using-workflows/reusing-workflows#example-reusable-workflow
name: hello-world reusable workflow

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        default: '["ubuntu-latest"]'
        type: string
      who-to-greet:
        description: Who to greet
        required: false
        default: World
        type: string

jobs:
  hello-world:
    name: reusable workflow hello world
    runs-on: ${{ fromJSON(inputs.runs-on) }}

    steps:
      - name: check GITHUB_REF
        run: echo ${{ env.GITHUB_REF }}

      - name: run a hello-world docker based GitHub Action
        # https://docs.github.com/en/actions/learn-github-actions/variables
        uses: JasonCubic/ga-hello-world@${{ env.GITHUB_REF }}
        with:
          greeting: Hello
          who-to-greet: ${{ inputs.who-to-greet }}
