# https://docs.github.com/en/actions/using-workflows/reusing-workflows#example-reusable-workflow
name: hello-world reusable workflow

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        default: '["ubuntu-latest"]'
        type: string
      who-to-greet:
        description: Who to greet
        required: false
        default: World
        type: string

jobs:
  hello-world:
    name: reusable workflow hello world
    runs-on: ${{ fromJSON(inputs.runs-on) }}

    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
    
    
#       - name: test ref values
#         run: |
#           echo "github.action_ref: ${{ github.action_ref }}"
#           echo "github.base_ref: ${{ github.base_ref }}"
#           echo "github.head_ref: ${{ github.head_ref }}"
#           echo "github.ref: ${{ github.ref }}"
#           echo "github.workflow_ref: ${{ github.workflow_ref }}"
#           echo "github.job_workflow_sha: ${{ github.job_workflow_sha }}"
      - name: run a hello-world docker based GitHub Action
        # https://docs.github.com/en/actions/learn-github-actions/variables
        uses: JasonCubic/ga-hello-world@v0.0.4
        with:
          who-to-greet: ${{ inputs.who-to-greet }}
