# https://docs.github.com/en/actions/using-workflows/reusing-workflows#example-reusable-workflow
name: hello-world reusable workflow

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        default: '["ubuntu-latest"]'
        type: string
      who-to-greet:
        description: Who to greet
        required: false
        default: World
        type: string

jobs:
  hello-world:
    name: reusable workflow hello world
    runs-on: ${{ fromJSON(inputs.runs-on) }}

    steps:
      - name: outside of container hello-world
        run: |
          echo "github.ref_name ${{github.ref_name}}"
          echo "Hello $2"

      - name: run a hello-world docker based GitHub Action
        # https://docs.github.com/en/actions/learn-github-actions/variables
        uses: JasonCubic/ga-hello-world@v0.0.1
        with:
          who-to-greet: ${{ inputs.who-to-greet }}
