# https://docs.github.com/en/actions/using-workflows/reusing-workflows#example-reusable-workflow
name: hello-world reusable workflow

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        default: '["ubuntu-latest"]'
        type: string
      who-to-greet:
        description: Who to greet
        required: false
        default: World
        type: string

jobs:
  hello-world:
    name: reusable workflow hello world
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    # runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          # github-server-url: https://git.t3.daimlertruck.com
          # https://github.com/JasonCubic/ga-hello-world
          repository: JasonCubic/ga-hello-world
          ref: v0.0.1
          path: ./.github/actions/ga-hello-world

      - name: run a hello-world docker based GitHub Action
        uses: ./.github/actions/ga-hello-world
        with:
          who-to-greet: ${{ inputs.who-to-greet }}
